### ISSUE TITLE
Web API for Android side

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#141]

**Comment by umutafacan** [comment]
Signup, login api's are ready.
localhost:8080/cmpesocial/api/login
localhost:8080/cmpesocial/api/signup  addresses for localhost 

Sample Req&Response Jsons
Login Request 
{
    "email" :  "umut@boun.edu.tr",
    "password" : "1234"
}

Login Successful response:

{"type" :  "SUCCESS",
"user"  :  {"surname":"afacan",
"password":"81dc9bdb52d04dc20036dbd8313ed055",
"email" : "umut@boun.edu.tr",
"name" : "umut", 
"id" : 2
}}

Signup: 

{
      "name":"test",
      "surname" : "testson",
      "passoword":"1234a",
     "email" : "test@boun.edu.tr"
}

Succesful response
{
   "Result" : "Success"
}

**Comment by umutafacan** [comment]
{domain}/cmpesocial/api/updateUser  

{
    "id": 2,
    "email" :  "umut@boun.edu.tr",
    "password" : "1234",
    "name" : "otrivine",
    "surname" : "afacaaacan"  
}

Result : 
{"Result":"SUCCESS"}

**Comment by umutafacan** [comment]
[Event API’s.pdf](https://files.zenhub.io/564121e53b012229198153a1)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

The document for event api's are available link above

**Comment by tuba-topaloglu** [comment]
tested, works as expected
