### ISSUE TITLE
Preparing a introduction/about page on web

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#147]

**Comment by cankurtan** [comment]
Our system will have an introduction page for visitors. Now we dont have restriction for visitors, they can see pages. In the last version we will close the system only for members. Visitors will have permission to see only introduction page and registration page.

**Comment by danishjo** [comment]
We have a welcome page UI @cankurtan 
Please check ==> 4519397a143ee9e5984cdaa573c2ee88a5514784

Do we need an extra page for "about"? if so, I will create that page.

**Comment by cankurtan** [comment]
added to web.
