### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#171]
Events API improvements:
    events/all - data sent needs to be encoded in UTF-8
    A function is needed to view the details of an with id
User API improvements:
    a function is needed to get profile info of a user with his/her id

**Comment by umutafacan** [comment]
events/viewDetail 
Resquest
{
"id" : 1
}
, events/getParticipants
Request:
{
"id" : 1
}

**Comment by tuba-topaloglu** [comment]
implement additional functions to see info of all users and search for a user with his/her id

**Comment by umutafacan** [comment]
api/getUser
{
"id":1
}

**Comment by 3m00ns** [comment]
Write fucntions to get all users, all users with a given role etc.

**Comment by tuba-topaloglu** [comment]
Testes, works as expected.
