### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#185]
Implement the necessary code to let the users have roles

**Comment by umutafacan** [comment]
user roles(types) db, sql, api changes done for groups. (events and web controllers are still implementing)

**Comment by umutafacan** [comment]
done. to look changes after build target/miredot/index.html documentation page will help. #android

**Comment by tuba-topaloglu** [comment]
Roles are implemented, and fast tested. If a bug is found, a new issue will be opened, thus this one is closed.
