### ISSUE TITLE
Frontend to Backend Enhancement

### ISSUE THREAD

**Issue by danishjo** [bounswe/bounswe2015group3#187]
- Adding post to events.
- Connecting search screen to backend.
- Connecting group page to backend.

**Comment by cankurtan** [comment]
Exact search is done and connected to every screen which has search bar. Search can be used for tags after tag backend is done. Rest of the job is postponed to milestone 3.

**Comment by cankurtan** [comment]
Closed mistakenly

**Comment by cankurtan** [comment]
What I have done:
- Group create page is connected to backend.
- Group view page is connected to backend.
- Post creation under group page is connected to backend.
- Listing posts under group page is done.
- Groups page is created and connected to backend.
- Created groups are listed in the main page.
- Links goes to group related page are corrected.
- SQL and controller mistakes are corrected.
