### ISSUE TITLE
Group's Database, Controller and API

### ISSUE THREAD

**Issue by danishjo** [bounswe/bounswe2015group3#188]
- Write functions for group features
- Database Configuration

**Comment by umutafacan** [comment]
@danishjo  @cankurtan  group controller yazdım postlar da dahil akşam düzeltirim bi problem varsa.
@3m00ns @BurakYilmaz92 mobile api'de sorun vardı Burak sağolsun onu düzelttim.

**Comment by tuba-topaloglu** [comment]
Tested, API works fine.
