### ISSUE TITLE
Android - Post Creation & Event Fix

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#206]
Implement the functionality to add posts to events.
Addtionally, fix the bugs in events.

**Comment by tuba-topaloglu** [comment]
bugs in the events are fixed. #215 is a child of this issue.
post creation is still missing.

**Comment by ghost** [comment]
post creation, deletion, and update can be found under android_event

**Comment by tuba-topaloglu** [comment]
merged to android branch, fast tested, works as expected.
