### ISSUE TITLE
Android Leave Event Does Not Work

### ISSUE THREAD

**Issue by ghost** [bounswe/bounswe2015group3#217]

**Comment by tuba-topaloglu** [comment]
The backend functionality for it is not implemented yet, this is not a bug.

**Comment by umutafacan** [comment]
leave event and leave group api's are ready 
/groups/leave 
{
"id_group":1,
"id_user":1
}

/events/leave
{
"id_event":1,
"id_user":1
}

**Comment by tuba-topaloglu** [comment]
tested, works as expected and thus, this issue is closed.
