### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#225]
Groups: 
     \* isMember should be a boolean value, it will be easier to parse.
     \* Methods related to comments should be implemented.

Events:
    \* A method to leave an event should be implemented. 
    \* Methods to invite users to events should be implemented.

Type in events and groups:
    \* type of events and groups should have a default value, for example, is 0 or null is sent from a client, all users are accepted to an event or a group.

**Comment by tuba-topaloglu** [comment]
Events:
    \* Add a field to events hasJoined, like isMember of group
User:
    \* Implement a method to return the list of events the user has joined.
    \* Implement a method to return the list of groups the user has joined.

**Comment by tuba-topaloglu** [comment]
Add the following boolean fields to events and groups tables, so that the Android application gets this information when it calls events/view or groups/view API: 
    \* "hasJoined"/"isMember"
    \* "isInvitedTo"

PS: The names of the fields are just examples.

**Comment by umutafacan** [comment]
done

**Comment by tuba-topaloglu** [comment]
tested, works as expected.

**Comment by tuba-topaloglu** [comment]
User API:
    \* Implement a method to change the profile picture of the user.
    \* getUser doesn't return the field profile_pic_link.

Event API:
    \* Type 0 means all. Does it work correctly?

Group API:
    \* Implement method to get the events of a group.

Search API:
    \* Implement method to search groups.

**Comment by tuba-topaloglu** [comment]
done except for group api, closed for now. 
PS: Event system is changed, we don't use 0 for all types any more.
