### ISSUE TITLE
Event edit and delete options

### ISSUE THREAD

**Issue by cankurtan** [bounswe/bounswe2015group3#235]
We need a control for who can edit and delete events. Only creator of the event can do these operations.

**Comment by ozencem** [comment]
Added control so that only the creator of the event can delete or edit it.

**Comment by ozencem** [comment]
Done

**Comment by cankurtan** [comment]
Now we have backend check after someone clicked to edit/delete button. But also we should make that buttons visible only for event owners. Checking who made changes after data sended to controller is necessary for security part and you already did this part. But as a main functionality we need a edit/delete button in page and event view screens. So you should create a boolean(true for event owner, false for others) for view scren.

**Comment by ozencem** [comment]
In the event view, a boolean value called isOwner is sent, true if the owner is the current user, false otherwise. Now we need to connect this to front-end.

**Comment by cankurtan** [comment]
Necessary parts are added. Delete works fine but edit option has a bug. It is related with #264.
