### ISSUE TITLE
Group edit and delete operations

### ISSUE THREAD

**Issue by cankurtan** [bounswe/bounswe2015group3#236]
We need a control for who can edit and delete groups. Only creator of the group can do these operations.

**Comment by ozencem** [comment]
Done.

**Comment by cankurtan** [comment]
As I explained in event edit/delete issue, same problem occurs here. We need a boolean in fronted to show edit/delete button in group view.

**Comment by ozencem** [comment]
In the group view, a boolean value called isOwner is sent. The value is true if the creator of the group is the current user, false otherwise. Now we need a front-end for this.

**Comment by cankurtan** [comment]
Necessary parts are changed. Edit and delete options are added for the group owner. Bug for group update function is found. Bug is fixed.
