### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by BurakYilmaz92** [bounswe/bounswe2015group3#239]
my commit:  https://github.com/bounswe/bounswe2015group3/commit/54dc9736d07d45d0858192b3e1b6744218a5c08b

Could you please review the commit I mentioned?
In this commit, I created function of creating group action and showing all groups in mobile platform

**Comment by tuba-topaloglu** [comment]
First of all, nicely written code, thanks for contribution. 
However some points that could be improved are:
    \* There are some unused variables in NewGroupActivity such as startDateEditText etc. 
    \* Similarly Group class has some unused variables.
Except for the above mentioned matters, the code is bug-free and easy to understand. The names of the variables make sense. There are no comments in the code, but I don't think this is a problem in this case, as the variable and method names are chosen well and the coding style is easy to follow and read through.
As a side note, the built-in code inspector suggests that LinearLayout in a ScrollView should have "wrap_content" as its height.
