### ISSUE TITLE
Leave event functionality

### ISSUE THREAD

**Issue by ozencem** [bounswe/bounswe2015group3#243]

**Comment by ozencem** [comment]
I added the controller part for leaving an event. Additionally, a button is needed for a user to leave an event, similar to the join event button.

**Comment by cankurtan** [comment]
We don't know when we show the event leave button instead of join event button in frontend. So we need a boolean(true if already joined, otherwisefalse) for event view to check someone already joined to event or not.

**Comment by ozencem** [comment]
A boolean is sent to front end called "going" and front-end is also modified to show either "join" or "leave" depending on the user's participation to an event.

**Comment by ozencem** [comment]
Assigned to BurakYilmaz92 for testing

**Comment by BurakYilmaz92** [comment]
Done !
