### ISSUE TITLE
Leave group functionality

### ISSUE THREAD

**Issue by ozencem** [bounswe/bounswe2015group3#244]

**Comment by ozencem** [comment]
The leave group button is working now.

**Comment by cankurtan** [comment]
We don't know when we show the leave group button instead of join group button in frontend. So we need a boolean(true if already joined, otherwise false) for group view.

**Comment by ozencem** [comment]
A boolean value is sent to the front-end now.

**Comment by ozencem** [comment]
Front-end is changed now to show either "Join Group" or "Leave Group" depending on the user's current membership status to the group.

**Comment by ozencem** [comment]
Assigning this to BurakYilmaz92 for testing.

**Comment by BurakYilmaz92** [comment]
Done !
