### ISSUE TITLE
Mail check for register

### ISSUE THREAD

**Issue by cankurtan** [bounswe/bounswe2015group3#246]
Now we accept all registers. We need a check for same email usage. If user tries to register with an email which have already registered we should redirect it to register screen with an error

**Comment by ozencem** [comment]
Now we do not allow the same mail address when registering. However, we still need to implement a way to show errors in our front end.

**Comment by danishjo** [comment]
User interface for alert added. Please checkout ==> fb3d75386f306c2ae3aa3486f281b04e4796f144
