### ISSUE TITLE
Event Creation - Periodic

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#247]
Add a SelectList to let the user create periodic events. 
Events can be:
    \* not periodic (0)
    \* weekly (1)
    \* monthly (2)
    \* yearly (3)
The periods are stored as integer values (as shown above).

![screen shot 2015-12-13 at 20 02 14](https://cloud.githubusercontent.com/assets/3121009/11768395/8a5810e6-a1d4-11e5-8c61-b8093d9a546a.png)

**Comment by cankurtan** [comment]
It is done. Ready for tests

**Comment by BurakYilmaz92** [comment]
Tests are done. It seems like no problem, but  as end user , I cant see whether event is periodic or who can join in event detail page.MAybe we can show these details in event detailed show page.
