### ISSUE TITLE
Simple Tag Web Controller

### ISSUE THREAD

**Issue by umutafacan** [bounswe/bounswe2015group3#252]
tag database objects and classes are ready. 

For user,event and group
there are 4 method:
-add tag
-delete tag
-tags for object
-objects for tag

**Comment by ozencem** [comment]
Need clarification.

**Comment by umutafacan** [comment]
Adding additional functions  or datas to response by using methods in TagDAO
to eventController, groupController, and userController
such as 
 -add tag to event method
-putting tags of event to data of event when viewing an event etc

API's can be refence.  Also talking with @danishjo maybe needed to consider page flows of frontend

**Comment by ozencem** [comment]
Tag creating functions are added for event and group. URL's for those are /event/tag/add and /group/tag/add. Now we need to create a form on the front-end in order to add tags to events and groups. @danishjo @cankurtan
