### ISSUE TITLE
Web user sign-out and sign-in 

### ISSUE THREAD

**Issue by BurakYilmaz92** [bounswe/bounswe2015group3#257]
In web platform, there is no option for changing profile. WE need sign-out and sign-in

**Comment by danishjo** [comment]
We have front-end for user profile => commit:  830fc734e7ea4d32dfe1ea2345de8b11c12456c7

here is the link for profile.html => https://github.com/bounswe/bounswe2015group3/blob/master/frontend/profile.html

**Comment by BurakYilmaz92** [comment]
I just mean that I can't sign out as a end user. Sign out button doesnt work

**Comment by ozencem** [comment]
Sign out button works now. => commit: ef815e2b828e59e6e0cc3f652705454fa3c8ecc1

**Comment by BurakYilmaz92** [comment]
Done !
