### ISSUE TITLE
Error Page

### ISSUE THREAD

**Issue by cankurtan** [bounswe/bounswe2015group3#275]
We need an error page. We will send a message about why that error occured. This page will show the error in a red labeled box or something like that.

**Comment by danishjo** [comment]
I tried to revert the previous commit. I think I couldn't. 
Please Ignore the commit.

**Comment by danishjo** [comment]
@cankurtan  Checkout the alert messages ==> fb3d75386f306c2ae3aa3486f281b04e4796f144
